<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-J37D3H2" failures="4" tests="8" name="BankingApp Test" time="68.931" errors="0" timestamp="2021-05-06T09:47:23 IST">
  <testcase classname="pom.inetbaking.testcases.TC_Login_001" name="LoginTest001" time="1.779"/>
  <testcase classname="pom.inetbaking.testcases.TC_CreateCustomer_002" name="Custlogin" time="5.279"/>
  <testcase classname="pom.inetbaking.testcases.TC_UploadFile_003" name="uploadfile" time="3.52"/>
  <testcase classname="pom.inetbaking.testcases.TestCaseforDDT" name="DDT" time="3.144">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pom.inetbaking.testcases.TestCaseforDDT.DDT(TestCaseforDDT.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDT -->
  <testcase classname="pom.inetbaking.testcases.TestCaseforDDT" name="DDT" time="3.288">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pom.inetbaking.testcases.TestCaseforDDT.DDT(TestCaseforDDT.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDT -->
  <testcase classname="pom.inetbaking.testcases.TestCaseforDDT" name="DDT" time="3.404">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pom.inetbaking.testcases.TestCaseforDDT.DDT(TestCaseforDDT.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDT -->
  <testcase classname="pom.inetbaking.testcases.TestCaseforDDT" name="DDT" time="3.101">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pom.inetbaking.testcases.TestCaseforDDT.DDT(TestCaseforDDT.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDT -->
  <testcase classname="pom.inetbaking.testcases.TestCaseforDDT" name="DDT" time="4.41"/>
</testsuite> <!-- BankingApp Test -->
